package genfile

const View = `package tui

import (
	"fmt"

	"github.com/charmbracelet/lipgloss"
)


var keyParts = []string{
	" _______",
	"|\\     /",
	"| +---+ ",
	"| |   | ",
	"| |%s  | ",
	"| +---+ ",
	"|/_____\\",
}

func keySwitchArt(s string) string {
	var art string
	for i, line := range keyParts {
		for _, c := range s {
			if i == 4 {
				art += fmt.Sprintf(line, string(c))
			} else {
				art += line
			}
		}

		if i == 0 {
			art += "\n"
		} else {
			art += "|\n"
		}

	}

	return art
}

func MainView(s string) string {
	titleView := keySwitchArt(s)
	descView := "Generated by drexler, with love ❤️"
	quitView := lipgloss.NewStyle().Faint(true).SetString("[ctrl+c to quit]").String()

	return "\n" + titleView + "\n" + descView + "\n\n\n\n\n" + quitView + "\n"
}

`
