package genfile

const View = `package tui

import (
	"fmt"

	"github.com/charmbracelet/lipgloss"
)


var keyParts = []string{
	" _______",
	"|\\     /",
	"| +---+ ",
	"| |   | ",
	"| |%s  | ",
	"| +---+ ",
	"|/_____\\",
}

func keySwitchArt(s string) string {
	art := "\n"
	for i, line := range keyParts {
		for _, c := range s {
			if i == 4 {
				art += fmt.Sprintf(line, string(c))
			} else {
				art += line
			}
		}

		if i == 0 {
			art += "\n"
		} else {
			art += "|\n"
		}

	}

	art += "\n"

	return art
}

func titleView(appName string) string {
	return keySwitchArt(appName)
}

func descView() string {
	return "Hello, it's your World "
}

func footerView() string {
	return lipgloss.NewStyle().Faint(true).SetString("\n\n\n\nGenerated by drexler, with love ❤️\n[ctrl+c to quit]\n").String()
}

`
